#!/bin/bash
set -e

cp -R svg/ build/svg
cp style.css build/style.css
cp index.html build/index.html
cp talks.html build/talks.html
cp software.html build/software.html
cp favicon.ico build/favicon.ico

s3cmd sync --recursive --cf-invalidate build/ s3://iacutone
echo -e "\t Successfully deployed to S3 and CloudFront cache invalidated"
